// Mocks generated by Mockito 5.4.6 from annotations
// in trilho/test/core/services/geofencing_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:trilho/core/models/crowd_model.dart' as _i2;
import 'package:trilho/core/models/line_model.dart' as _i8;
import 'package:trilho/core/models/station_arrivals_model.dart' as _i4;
import 'package:trilho/core/models/station_model.dart' as _i9;
import 'package:trilho/core/models/usage_model.dart' as _i3;
import 'package:trilho/core/services/api_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCrowdModel_0 extends _i1.SmartFake implements _i2.CrowdModel {
  _FakeCrowdModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsageModel_1 extends _i1.SmartFake implements _i3.UsageModel {
  _FakeUsageModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStationArrivals_2 extends _i1.SmartFake
    implements _i4.StationArrivals {
  _FakeStationArrivals_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  void setToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<Map<String, dynamic>> register() => (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<_i8.LineModel>> getLines() => (super.noSuchMethod(
        Invocation.method(
          #getLines,
          [],
        ),
        returnValue: _i7.Future<List<_i8.LineModel>>.value(<_i8.LineModel>[]),
      ) as _i7.Future<List<_i8.LineModel>>);

  @override
  _i7.Future<Map<String, dynamic>> getLineStatus(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLineStatus,
          [code],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i2.CrowdModel> getStationCrowd(int? stationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStationCrowd,
          [stationId],
        ),
        returnValue: _i7.Future<_i2.CrowdModel>.value(_FakeCrowdModel_0(
          this,
          Invocation.method(
            #getStationCrowd,
            [stationId],
          ),
        )),
      ) as _i7.Future<_i2.CrowdModel>);

  @override
  _i7.Future<_i3.UsageModel> getUsage() => (super.noSuchMethod(
        Invocation.method(
          #getUsage,
          [],
        ),
        returnValue: _i7.Future<_i3.UsageModel>.value(_FakeUsageModel_1(
          this,
          Invocation.method(
            #getUsage,
            [],
          ),
        )),
      ) as _i7.Future<_i3.UsageModel>);

  @override
  _i7.Future<Map<String, dynamic>> loginWithSocial({
    required String? provider,
    required String? idToken,
    String? displayName,
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithSocial,
          [],
          {
            #provider: provider,
            #idToken: idToken,
            #displayName: displayName,
            #email: email,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<_i9.StationModel>> getStations() => (super.noSuchMethod(
        Invocation.method(
          #getStations,
          [],
        ),
        returnValue:
            _i7.Future<List<_i9.StationModel>>.value(<_i9.StationModel>[]),
      ) as _i7.Future<List<_i9.StationModel>>);

  @override
  _i7.Future<Map<String, dynamic>> loginWithFirebase(String? idToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithFirebase,
          [idToken],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> postPing({
    required double? lat,
    required double? lng,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postPing,
          [],
          {
            #lat: lat,
            #lng: lng,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i4.StationArrivals> getStationArrivals(int? stationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStationArrivals,
          [stationId],
        ),
        returnValue:
            _i7.Future<_i4.StationArrivals>.value(_FakeStationArrivals_2(
          this,
          Invocation.method(
            #getStationArrivals,
            [stationId],
          ),
        )),
      ) as _i7.Future<_i4.StationArrivals>);
}
