// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trilho.Infrastructure.Persistence;

#nullable disable

namespace Trilho.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321123955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trilho.Domain.Entities.CrowdSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("DensityLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("density_level");

                    b.Property<decimal>("InferredDensity")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("inferred_density");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer")
                        .HasColumnName("user_count");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "CapturedAt");

                    b.ToTable("crowd_snapshots");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.HistoricalDemand", b =>
                {
                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<string>("DayType")
                        .HasColumnType("text")
                        .HasColumnName("day_type");

                    b.Property<short>("Hour")
                        .HasColumnType("smallint")
                        .HasColumnName("hour");

                    b.Property<int>("AvgPassengers")
                        .HasColumnType("integer")
                        .HasColumnName("avg_passengers");

                    b.HasKey("StationId", "DayType", "Hour");

                    b.ToTable("historical_demands");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("char(6)")
                        .HasColumnName("color_hex");

                    b.Property<int>("HeadwayOffPeakSec")
                        .HasColumnType("integer")
                        .HasColumnName("headway_off_peak_sec");

                    b.Property<int>("HeadwayPeakSec")
                        .HasColumnType("integer")
                        .HasColumnName("headway_peak_sec");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("lines");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.LineStatusEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LineId", "CapturedAt");

                    b.ToTable("line_status", (string)null);
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("stations");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyQueriesUsed")
                        .HasColumnType("integer")
                        .HasColumnName("daily_queries_used");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<DateOnly>("QueriesResetAt")
                        .HasColumnType("date")
                        .HasColumnName("queries_reset_at");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.UserPing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("UserId");

                    b.ToTable("user_pings");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.CrowdSnapshot", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Station", "Station")
                        .WithMany("CrowdSnapshots")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.HistoricalDemand", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Station", "Station")
                        .WithMany("HistoricalDemands")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.LineStatusEntry", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Line", "Line")
                        .WithMany("StatusHistory")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Station", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Line", "Line")
                        .WithMany("Stations")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.UserPing", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trilho.Domain.Entities.User", "User")
                        .WithMany("Pings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Line", b =>
                {
                    b.Navigation("Stations");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Station", b =>
                {
                    b.Navigation("CrowdSnapshots");

                    b.Navigation("HistoricalDemands");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.User", b =>
                {
                    b.Navigation("Pings");
                });
#pragma warning restore 612, 618
        }
    }
}
