// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trilho.Infrastructure.Persistence;

#nullable disable

namespace Trilho.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trilho.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admin_users");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("Name", "State")
                        .IsUnique();

                    b.ToTable("cities");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.CrowdSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("DensityLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("density_level");

                    b.Property<decimal>("InferredDensity")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("inferred_density");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer")
                        .HasColumnName("user_count");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "CapturedAt");

                    b.ToTable("crowd_snapshots");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.GtfsAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agency_id");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_name");

                    b.Property<string>("AgencyTimezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_timezone");

                    b.Property<string>("AgencyUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency_url");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId")
                        .IsUnique();

                    b.ToTable("gtfs_agencies");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.GtfsCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean")
                        .HasColumnName("friday");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean")
                        .HasColumnName("monday");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean")
                        .HasColumnName("saturday");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean")
                        .HasColumnName("sunday");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean")
                        .HasColumnName("thursday");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean")
                        .HasColumnName("tuesday");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean")
                        .HasColumnName("wednesday");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("gtfs_calendars");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.GtfsRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agency_id");

                    b.Property<string>("RouteColor")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("route_color");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteLongName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_long_name");

                    b.Property<string>("RouteShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_short_name");

                    b.Property<string>("RouteTextColor")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("route_text_color");

                    b.HasKey("Id");

                    b.HasIndex("RouteId")
                        .IsUnique();

                    b.ToTable("gtfs_routes");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.GtfsStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("StopCode")
                        .HasColumnType("text")
                        .HasColumnName("stop_code");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stop_id");

                    b.Property<double>("StopLat")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_lat");

                    b.Property<double>("StopLon")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_lon");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_name");

                    b.HasKey("Id");

                    b.HasIndex("StopId")
                        .IsUnique();

                    b.ToTable("gtfs_stops");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.GtfsStopTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("text")
                        .HasColumnName("arrival_time");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("text")
                        .HasColumnName("departure_time");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stop_id");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("stop_sequence");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "StopSequence");

                    b.ToTable("gtfs_stop_times");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.GtfsTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DirectionId")
                        .HasColumnType("boolean")
                        .HasColumnName("direction_id");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("TripHeadsign")
                        .HasColumnType("text")
                        .HasColumnName("trip_headsign");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("gtfs_trips");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.HistoricalDemand", b =>
                {
                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<string>("DayType")
                        .HasColumnType("text")
                        .HasColumnName("day_type");

                    b.Property<short>("Hour")
                        .HasColumnType("smallint")
                        .HasColumnName("hour");

                    b.Property<int>("AvgPassengers")
                        .HasColumnType("integer")
                        .HasColumnName("avg_passengers");

                    b.HasKey("StationId", "DayType", "Hour");

                    b.ToTable("historical_demands");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("code");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("char(6)")
                        .HasColumnName("color_hex");

                    b.Property<int>("HeadwayOffPeakSec")
                        .HasColumnType("integer")
                        .HasColumnName("headway_off_peak_sec");

                    b.Property<int>("HeadwayPeakSec")
                        .HasColumnType("integer")
                        .HasColumnName("headway_peak_sec");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("lines");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.LineStatusEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LineId", "CapturedAt");

                    b.ToTable("line_status", (string)null);
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<int>("LineId")
                        .HasColumnType("integer")
                        .HasColumnName("line_id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("stations");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveBillingId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("active_billing_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentPaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_payment_method");

                    b.Property<int>("DailyQueriesUsed")
                        .HasColumnType("integer")
                        .HasColumnName("daily_queries_used");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymous");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<DateTime?>("IsPremiumUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("is_premium_until");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vip");

                    b.Property<DateOnly>("QueriesResetAt")
                        .HasColumnType("date")
                        .HasColumnName("queries_reset_at");

                    b.Property<DateTime?>("SubscriptionCancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_cancelled_at");

                    b.Property<bool>("SubscriptionCancelledByUser")
                        .HasColumnType("boolean")
                        .HasColumnName("subscription_cancelled_by_user");

                    b.Property<DateTime?>("SubscriptionStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_started_at");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.Property<string>("VipEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("vip_email");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.UserDeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_notified_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_device_tokens");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.UserPing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("UserId");

                    b.ToTable("user_pings");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.CrowdSnapshot", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Station", "Station")
                        .WithMany("CrowdSnapshots")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.HistoricalDemand", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Station", "Station")
                        .WithMany("HistoricalDemands")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Line", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.City", "City")
                        .WithMany("Lines")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.LineStatusEntry", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Line", "Line")
                        .WithMany("StatusHistory")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Station", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Line", "Line")
                        .WithMany("Stations")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.UserDeviceToken", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.UserPing", b =>
                {
                    b.HasOne("Trilho.Domain.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trilho.Domain.Entities.User", "User")
                        .WithMany("Pings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.City", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Line", b =>
                {
                    b.Navigation("Stations");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.Station", b =>
                {
                    b.Navigation("CrowdSnapshots");

                    b.Navigation("HistoricalDemands");
                });

            modelBuilder.Entity("Trilho.Domain.Entities.User", b =>
                {
                    b.Navigation("DeviceTokens");

                    b.Navigation("Pings");
                });
#pragma warning restore 612, 618
        }
    }
}
